version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      # Mount current directory into /app inside container (for development changes)
      - .:/app
      # Mount a volume for the SQLite database so data persists across container restarts
      - app_data:/app/
    environment:
      # Load environment variables from a .env file
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    # For development, you might want to watch for code changes and restart
    # command: python app.py
    # depends_on:
    #   - db # If you switch to PostgreSQL, you'd add a 'db' service here

volumes:
  app_data: